%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/control511/Dynaslam/TUM_data/rgbd_dataset_freiburg3_walking_static

# camera intrinsics
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

# fr2
#cSSamera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 5000

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 30
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
N:6
V0:10
V1:5
/buffernumber: 1000
/fx: 517.3
/fy: 516.5
/cx: 325.1 
/cy: 249.7
/width: 640
/height: 480

